name: 'Create TS compiler reproductions in an issue'
description: 'Does what it says on the tin'
author: 'Microsoft'
inputs:
  github-token:
    description: 'API token for GitHub requests'
    required: true

  label:
    description: 'What label should be on an issue to indicate it has a repro?'
    default: 'Has Repro'

  repo:
    description: 'What repo should this action look at, if not set it uses the same repo'

  code-tag:
    description: 'What tag should be applied to the markdown code block?'
    default: 'repro'

runs:
  using: 'node12'
  main: 'dist/index.js'
